# clinicaltrials.gov
ctgov:
  image: tutum.co/roll/opentrials-scraper
  command: scrapy crawl ctgov -a date_from=2001-01-01
  restart: always
  environment:
    OPENTRIALS_DATABASE_URL:
    OPENTRIALS_DOWNLOAD_DELAY: 10

# isrctn.com
isrctn:
  image: tutum.co/roll/opentrials-scraper
  command: scrapy crawl isrctn -a date_from=2001-01-01
  restart: always
  environment:
    OPENTRIALS_DATABASE_URL:
    OPENTRIALS_DOWNLOAD_DELAY: 10
